### ISSUE TITLE
[Feature]: Stream chat output

### ISSUE THREAD

**Issue by Micost** [SkywardAI/kirin#144]
### Contact Details

zmicost@gmail.com

### What feature are you requesting?

Use existing api or create a new api for stream chat output. The could reduce the response time and make output more realistic .

**Comment by cbh778899** [comment]
I've found a way to use SSE (Server-Sent Events) that can send response multiple times using only one connection, see [MDN Reference](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events), and here is an [example](https://stackoverflow.com/a/59041709) of python implement.

The spirit is, which i believes, is the response header should have `"Content-Type":"text/event-stream"` and `"Connection":"keep-alive"`

**Comment by Aisuko** [comment]
cc @Micost @jinronga Hi, guys. Take a look at the idea of stream.
