### ISSUE TITLE
[Feature]: The `version` API should return the components we are using

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/kirin#174]
### What feature are you requesting?

Currently, we only return version of the backend. We want to get more:

* backend
* llamacpp
* Vector db

https://github.com/SkywardAI/chat-backend/blob/0321b7946d0dbbde1e0a692986a923c0e8a9d1c9/backend/src/api/routes/version.py#L28-L29

@Micost

**Comment by Aisuko** [comment]
More see here
https://github.com/SkywardAI/chat-backend/blob/b861c2116d2fb4353fdfa50377b1785e14ba6892/backend/src/config/settings/base.py#L78-L81

**Comment by Micost** [comment]
Closed per PR #187
