### ISSUE TITLE
[Feature]: Suggestions on chat APIs

### ISSUE THREAD

**Issue by cbh778899** [SkywardAI/kirin#178]
### What feature are you requesting?

- [x]  remove `GET /api/chat`, this can cause serious privacy issues. https://github.com/SkywardAI/kirin/pull/203

- [x] Add api to generate a token for anonymous users before they can start any conversation, this should be the identifier temporarily https://github.com/SkywardAI/kirin/pull/203

- [x] APIs requests should pass user token for validation, token should be changed on each login/register/anonymous query, should have expire time - e.g. 24hrs, should can extract logged-in user id somehow to append to user history, instead of pass user id that anonymous users doesn't have, and pass id is not safe as well. https://github.com/SkywardAI/kirin/pull/203

- [x] `POST /api/chat` session id should return a complex string to avoid information leak. add also token in coming request. e.g. request should be
> POST xxx/api/chat HTTP/1.1
> Content-Type: application/json
> 
> {
>     token: string,
>     sessionId?: string,
>     message: string
> }

- [x]  `GET /api/chat` doesn't seems to work at this moment, should also add token, a better way could be `GET /api/chat?id=?&token=?`

- [ ] #240

**Comment by Aisuko** [comment]
- [ ] #180

**Comment by Aisuko** [comment]
As we discussed, we need to make a solution for this.
