### ISSUE TITLE
[Feature]: Let's docs APIs

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/kirin#201]
### What feature are you requesting?

We should add more docs, example for the APIs. Here are the examples:

- https://fastapi.tiangolo.com/tutorial/metadata/
- https://stackoverflow.com/a/71400955/6712353
- https://fastapi.tiangolo.com/how-to/configure-swagger-ui/
- https://fastapi.tiangolo.com/tutorial/schema-extra-example/?h=
- https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#tags

**Comment by Lijinyu3** [comment]
@Aisuko
