### ISSUE TITLE
[Feature]: Configurable database and vector db behavior when serverice start

### ISSUE THREAD

**Issue by Micost** [SkywardAI/kirin#244]
### What feature are you requesting?

We currently drop database/collections and recreate again when backend service start.  This is a acceptable strategy for dev env.  But this will case issue in prod env. 

We should have the database and vector db behavior configurable.

for dev env,   we should drop and recreate database/collections as we currently do 

for prd env,   we only run checks to make sure the data structure is the save as we defined in service

cc: @Aisuko

**Comment by Aisuko** [comment]
HI @Micost thank you. Let's make it configurable through

- https://github.com/SkywardAI/kirin/blob/main/backend/src/config/settings/development.py
- https://github.com/SkywardAI/kirin/blob/main/backend/src/config/settings/production.py
