### ISSUE TITLE
POST /api/chat/save should add createdAt attribute

### ISSUE THREAD

**Issue by cbh778899** [SkywardAI/kirin#252]
### What feature are you requesting?

Conversation history should have createdAt, passed by frontend, to make sure the conversation history is in right order. Request body should be like 
```
{
  “sessionUuid”:”uuid”,
  ”chats”: [
    {
      “role”:”user”,
      ”message”:”hello”,
      ”createdAt”:1234567890
    },
    {
      “role”:”assistant”,
      ”message”:”hi, how can I assist you today?”,
      ”createdAt”:1234567891
    }
  ]
}
```

**Comment by Aisuko** [comment]
I have talked to @Micost about this issue. He will return create date and re-order the conversation history. cc @cbh778899

**Comment by Aisuko** [comment]
@Micost Do we finish this one?

**Comment by Micost** [comment]
@Aisuko it's already done
