### ISSUE TITLE
[Feature]: New API for removing session

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/kirin#273]
### What feature are you requesting?

Removing session by session uuid(only for logged user)

**Comment by jinronga** [comment]
![image](https://github.com/user-attachments/assets/4912d8d8-86d5-4f7f-8bea-4b1a3174b119)
Good morning guys, I have a question. Is it to delete the records in the session table based on uuid? Do we want to do physical deletion or logical deletion? @Micost @Aisuko

**Comment by Micost** [comment]
@jinronga what is the difference between logical and physical deletion ?

**Comment by jinronga** [comment]
Logical deletion is not a real deletion. It does not check the deleted data, but is used as an archive.

**Comment by jinronga** [comment]
I've seen that session data doesn't need to be archived. More important data can be deleted logically.

**Comment by Micost** [comment]
I prefer directly delete all data  which is physical deletion .  Because if we archive session ,  we have to have another logic to do the delete.   @Aisuko how about you

**Comment by Aisuko** [comment]
Hi, guys. We alway choose the most simple and efficient way to do that. So, in here we just remove it(physical) otherwise we need to add a new field like active for Session table at db. We don't have time to do that. @Micost @jinronga

**Comment by jinronga** [comment]
OK, I understand.
