### ISSUE TITLE
[feature]: Visualisation the embeddings data

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/kirin#79]

**Comment by CarterFaceySmith** [comment]
This might come under what @Janak04 has done for the RMIT embedding data in Cecilia repo?

**Comment by Aisuko** [comment]
> This might come under what @Janak04 has done for the RMIT embedding data in Cecilia repo?

Ah, right. Here we want to show the visualization result at the frontend. Let's leave this issue for the frontend contributor. I think the backend should also support the frontend
