### ISSUE TITLE
[quality]: Add mock suit test framework

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/kirin#90]
As the process of development, we add vector db and others. It is hard for us to do the real test cases in CI. So, we need to add mock API behaviour test cases rather than trying to start the real instance.

**Comment by Aisuko** [comment]
Hi @Micost @jinronga guys. We need a mock test framework for FastAPI. It can enhance the confidence when we maintain the repo. E.g: merge the PR. Please keep in mind. Thank you.

**Comment by CarterFaceySmith** [comment]
@Aisuko @Micost @jinronga @Janak04 

I looked into this a bit and did a bit of testing re the following implementation using `pytest`, seems it could work for our purposes?

## Install
1. `pip install pytest`
2. Put any test cases in the `tests` directory
3. Run with the `pytest` command

## Comments
FastAPI endpoints can be mocked using `pytest` fixtures to generate mock objects (see exampleTest.py for implementation), these can then be used with `requests` to simulate HTTP requests to our FastAPI endpoint. 

We could then integrate this with Github Actions CI/CD to run the tests as per existing checks.

## `exampleTest.py`
```
import pytest
from fastapi.testclient import TestClient
from app.main import app

@pytest.fixture
def client():
    return TestClient(app)

def test_read_item(client):
    response = client.get("/items/foo")
    assert response.status_code == 200
    assert response.json() == {"name": "Foo", "price": 42}
```

**Comment by Micost** [comment]
@Aisuko @CarterFaceySmith 
I add this issue into milestone 0.1.8  ,   I think pytest is a good choice . It covers the unit test and end-to-end test.

**Comment by Aisuko** [comment]
Hi guys. We already have some test cases with `Pytest` framework. However, these test cases are needed we have the whole components were deployed, like pgsql, vector db. We can't do that in the CI pipeline. It is un-efficiency(it will take 5-10 minutes every time, and we need to boost all the components). 

What we want to do now is that we want to use mock API framework to mock the API behaviour. It is make sure that every APIs behaviour got checked before the PR got merged.

So, here is my thinking. Feel free to edit, remove or add the `backend/tests` folder.

**Comment by Aisuko** [comment]
- https://plainenglish.io/blog/how-to-mock-fastapi-dependencies-in-pytest#test_fastapi_dependencypy
- https://testdriven.io/blog/fastapi-crud/#conclusion
- https://fastapi.tiangolo.com/tutorial/testing/

**Comment by Aisuko** [comment]
FastAPI's injection dependency feature doesn't work. So, the mock test framework can't be achieved. See https://github.com/tiangolo/fastapi/discussions/8127. And the PR https://github.com/SkywardAI/kirin/pull/270 includes test cases using FastAPI injection system. However, it doesn't work. We will not waste time in this issue.
